# docker-compose.yml
version: "3"
services:
  app:
    restart: on-failure
    container_name: social-mail-server
    image: ghcr.io/social-mail/social-mail-server-docker-container:main
    depends_on:
      - postgres
    environment:
      # Please ensure that the IP maps correctly to following HostName in your DNS settings
      # for letsencrypt to work correctly.
      SOCIAL_MAIL_HOST: mydomain.com
      HOST: 0.0.0.0
      PORT: 80
      SELF_HOST: true
      SOCIAL_MAIL_DB_SERVER: postgres
      SOCIAL_MAIL_DB_HOST: postgres
      SOCIAL_MAIL_DB_PORT: 5432
      SOCIAL_MAIL_DB_DATABASE: SocialMails
      SOCIAL_MAIL_DB_USER: postgres
      SOCIAL_MAIL_DB_PASSWORD: SocialMail2023

      # Not recommended if database resides outside the same physical machine
      SOCIAL_MAIL_DB_SSL: 'null'

      # -- Volume Storage Section -- 
      # Not recommended in production, comment following and uncomment s3 section

      SOCIAL_MAIL_STORAGE: volume
      SOCIAL_MAIL_STORAGE_PATH: /data/files

      # -- End of Volume Storage Section -- 

      # -- S3 Compatible Storage Section -- 
      # Uncomment following lines for production till End of section

      # SOCIAL_MAIL_STORAGE: s3
      # SOCIAL_MAIL_S3_END_POINT: https://STORAGE.STORAGE-PROVIDER.com
      # SOCIAL_MAIL_S3_BUCKET=BUCKETNAME
      # SOCIAL_MAIL_S3_ACCESS_KEY=ACCESS_KEY
      # SOCIAL_MAIL_S3_SECRET=SECRET

      # -- End of S3 Compatible Storage Section -- 

      # Change following value to production for live usage
      SOCIAL_MAIL_SSL_LE: staging
      # SOCIAL_MAIL_SSL_LE: production
      # SOCIAL_MAIL_SSL_LE_EMAIL=somebody@nowhere

    ports:
      - "80:80"
      - "443:443"
      - "25:25"
    volumes:
      - /var/lib/clamav
      - /data/cert
      - /data/files

  postgres:
    container_name: postgres-server
    restart: on-failure
    image: postgres:alpine3.18
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SocialMail2023
      POSTGRES_DB: SocialMails
      PGDATA: /data/db
    volumes:
      - /data/db
